# Generated by Django 2.2.6 on 2019-12-24 04:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0006_codilist'),
    ]

    operations = [
        migrations.AddField(
            model_name='codilist',
            name='added_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codilist',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
