# Generated by Django 2.2.6 on 2019-12-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0007_auto_20191224_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codilist',
            name='added_time',
        ),
        migrations.AlterField(
            model_name='codilist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
