# Generated by Django 2.2.6 on 2019-12-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0009_clothing_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
