# Generated by Django 2.2.6 on 2019-12-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0011_filemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemodel',
            name='img',
        ),
        migrations.AddField(
            model_name='filemodel',
            name='file',
            field=models.FileField(default='default.jpg', upload_to=''),
        ),
    ]
