# Generated by Django 2.2.6 on 2020-01-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomesticCurrent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField()),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('status', models.TextField(null=True)),
                ('temp', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('windchill_temp', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('rain', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('snow', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('wind_direction', models.TextField(null=True)),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalPredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(default='empty')),
                ('city_id', models.IntegerField()),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=15, null=True)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InternationalCurrent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=15, null=True)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=15, null=True)),
                ('weather_id', models.IntegerField()),
                ('weather_main', models.TextField()),
                ('weather_description', models.TextField()),
                ('weather_icon', models.TextField()),
                ('temperature', models.TextField()),
                ('feels_like', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('pressure', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('humidity', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('wind_speed', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('wind_direction', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('cloud', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('rain_one_hour', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('rain_three_hour', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('snow_one_hour', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('snow_three_hour', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('calculation_datatime', models.DateTimeField()),
                ('city_country', models.TextField()),
                ('city_id', models.IntegerField()),
                ('city_name', models.TextField()),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
