# Generated by Django 2.2.6 on 2019-12-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentWeather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField()),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('status', models.TextField()),
                ('temp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('windchill_temp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rain', models.DecimalField(decimal_places=2, max_digits=5)),
                ('snow', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wind_direction', models.TextField()),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='ShortPredictionWeather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('dong_code', models.BigIntegerField()),
                ('location', models.TextField()),
                ('publish_time', models.TextField()),
                ('next_zero_hour', models.IntegerField()),
                ('next_zero_temp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('next_zero_sky', models.IntegerField()),
                ('next_zero_rain', models.IntegerField()),
                ('next_zero_rain_prob', models.DecimalField(decimal_places=2, max_digits=5)),
                ('next_zero_wind_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('next_zero_wind_direction', models.IntegerField()),
                ('next_zero_humidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('next_one_hour', models.IntegerField()),
                ('next_one_temp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('next_one_sky', models.IntegerField()),
                ('next_one_rain', models.IntegerField()),
                ('next_one_rain_prob', models.DecimalField(decimal_places=2, max_digits=5)),
                ('next_one_wind_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('next_one_wind_direction', models.IntegerField()),
                ('next_one_humidity', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
