# Generated by Django 2.2.6 on 2019-12-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentweather',
            name='humidity',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='rain',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='snow',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='status',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='temp',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='wind_direction',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='wind_speed',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='windchill_temp',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='shortpredictionweather',
            name='dong_code',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shortpredictionweather',
            name='location',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='shortpredictionweather',
            name='next_one_hour',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shortpredictionweather',
            name='next_one_humidity',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='shortpredictionweather',
            name='next_one_rain',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shortpredictionweather',
            name='next_one_rain_prob',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='shortpredictionweather',
            name='next_one_sky',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shortpredictionweather',
            name='next_one_temp',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='shortpredictionweather',
            name='next_one_wind_direction',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shortpredictionweather',
            name='next_one_wind_speed',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='shortpredictionweather',
            name='next_zero_hour',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shortpredictionweather',
            name='next_zero_humidity',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='shortpredictionweather',
            name='next_zero_rain',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shortpredictionweather',
            name='next_zero_rain_prob',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='shortpredictionweather',
            name='next_zero_sky',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shortpredictionweather',
            name='next_zero_temp',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='shortpredictionweather',
            name='next_zero_wind_direction',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shortpredictionweather',
            name='next_zero_wind_speed',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='shortpredictionweather',
            name='publish_time',
            field=models.TextField(null=True),
        ),
    ]
